/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package ar.com.coder.ui.programador;

import ar.com.coder.objetos.PedidoSeguimiento;
import ar.com.coder.ui.programador.objetos.Dia;
import ar.com.coder.ui.programador.objetos.Tarea;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.HeadlessException;
import java.awt.Point;
import java.util.ArrayList;
import javax.swing.JFrame;


/**
 *
 * @author Torralba
 */
public class FrmProgramador extends JFrame {
    private ArrayList<PedidoSeguimiento> pedidos;

    public FrmProgramador(ArrayList<PedidoSeguimiento> pedidos) throws HeadlessException {
        this.pedidos = pedidos;
        initComponents();
        programador.setPreferredSize(new Dimension((int) ((programador.getRangoDias()+1)*(Dia.ANCHO)), Dia.ALTO));
    }
    
    /**
     * Creates new form FrmProgramador
     */
    public FrmProgramador() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane3 = new javax.swing.JScrollPane();
        programador = new Programador(pedidos)
        ;

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setExtendedState(JFrame.MAXIMIZED_BOTH);

        javax.swing.GroupLayout programadorLayout = new javax.swing.GroupLayout(programador);
        programador.setLayout(programadorLayout);
        programadorLayout.setHorizontalGroup(
            programadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1085, Short.MAX_VALUE)
        );
        programadorLayout.setVerticalGroup(
            programadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 518, Short.MAX_VALUE)
        );

        jScrollPane3.setViewportView(programador);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 1087, Short.MAX_VALUE)
                .addGap(14, 14, 14))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 520, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 17, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane3;
    private ar.com.coder.ui.programador.Programador programador;
    // End of variables declaration//GEN-END:variables
}
