/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ar.com.coder.ui;

import ar.com.coder.dominio.excel.ExcelPartidasLector;
import ar.com.coder.dominio.PartidaControlador;
import ar.com.coder.objetos.Partida;
import ar.com.coder.objetos.PartidaComparada;
import java.awt.HeadlessException;
import java.io.File;
import java.util.ArrayList;
import javax.swing.JFileChooser;

/**
 *
 * @author sysadmin
 */
public class AbmPartida extends javax.swing.JInternalFrame {
    private PartidaControlador partidaControlador;
    private ArrayList<PartidaComparada> partidasActulizables;
    /**
     * Creates new form AbmPartida
     */
    public AbmPartida() {
        partidaControlador=new PartidaControlador(ar.com.coder.Principal.connection);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        partidaFechaGrilla = new ar.com.coder.ui.grillas.PartidaFechaGrilla();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setTitle("Verificar Fechas Entrega de Partidas En Proceso ");

        jButton1.setText("Cargar Archivo");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTable1.setAutoCreateRowSorter(true);
        jTable1.setModel(partidaFechaGrilla);
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 885, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        cargarArchivo();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void cargarArchivo() throws HeadlessException {
        ExcelPartidasLector partidasLector=new ExcelPartidasLector();
        partidasActulizables=new ArrayList<PartidaComparada>();
        JFileChooser fileChooser = new JFileChooser();
        int returnVal = fileChooser.showOpenDialog(this);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            File file = fileChooser.getSelectedFile();
            partidasLector.cargarArchivo(file);
            partidasLector.setNombreHoja("Proceso");
            for(Partida partidaExcel:partidasLector.extrearDatos()){
                Partida partidaNodum=partidaControlador.extraer(partidaExcel.getNroLote());
                if(partidaNodum==null){
                    continue;
                }
                if(!partidaNodum.getFechaEgresoProceso().equals(partidaExcel.getFechaEgresoProceso())){
                    partidasActulizables.add(new PartidaComparada(partidaNodum, partidaExcel));
                }
            }
            partidaFechaGrilla.setData(partidasActulizables);
            partidaFechaGrilla.fireTableDataChanged();
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private ar.com.coder.ui.grillas.PartidaFechaGrilla partidaFechaGrilla;
    // End of variables declaration//GEN-END:variables
}
