/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ar.com.coder.ui;

import ar.com.coder.Principal;
import ar.com.coder.dominio.PedidoSeguimientoControlador;
import ar.com.coder.objetos.PedidoSeguimiento;
import ar.com.coder.ui.grillas.PedidoTerminarGrilla;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author sysadmin
 */
public class GrillaPedidoTerminar extends javax.swing.JInternalFrame {

    private PedidoSeguimientoControlador psc;
    private ArrayList<PedidoSeguimiento> datos;
    private int[] filaSeleccionadas;
    private final PedidoTerminarGrilla grilla;
    private TableRowSorter trsGrilla;

    /**
     * Creates new form GrillaPedidoTerminar
     */
    public GrillaPedidoTerminar() {

        initComponents();
        this.trsGrilla = new TableRowSorter<PedidoTerminarGrilla>();
        psc = new PedidoSeguimientoControlador(Principal.connection);
        grilla = new PedidoTerminarGrilla();
        trsGrilla.setModel(grilla);
        jtGrilla.setModel(grilla);
        jtGrilla.setRowSorter(trsGrilla);
        actualizar();
    }

    private void actualizar() {
        datos = psc.extraerPedidoaTerminar();
        grilla.setData(datos);
        grilla.fireTableDataChanged();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jtGrilla = new javax.swing.JTable();
        jbTerminarPedidos = new javax.swing.JButton();
        jbCancelar = new javax.swing.JButton();

        setTitle("Pedidos a Terminar");

        jtGrilla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jtGrilla);

        jbTerminarPedidos.setText("Terminar Pedidos");
        jbTerminarPedidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbTerminarPedidosActionPerformed(evt);
            }
        });

        jbCancelar.setText("Cancelar");
        jbCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 612, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbTerminarPedidos, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbCancelar)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbTerminarPedidos)
                    .addComponent(jbCancelar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbTerminarPedidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbTerminarPedidosActionPerformed
        filaSeleccionadas = jtGrilla.getSelectedRows();
        int rtn;
        rtn = JOptionPane.showConfirmDialog(this, "Desea Terminar los pedidos Seleccionados?", "Advertencia", JOptionPane.YES_NO_CANCEL_OPTION);
        if (rtn == JOptionPane.YES_OPTION) {
            for (int fila : filaSeleccionadas) {
                PedidoSeguimiento ps = datos.get(fila);
                if (!psc.terminarPedido(ps)) {
                    JOptionPane.showMessageDialog(this, "No se puede terminar Pedido:" + ps.getIdPedido());
                }
            }
        }
        actualizar();
    }//GEN-LAST:event_jbTerminarPedidosActionPerformed

    private void jbCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_jbCancelarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbCancelar;
    private javax.swing.JButton jbTerminarPedidos;
    private javax.swing.JTable jtGrilla;
    // End of variables declaration//GEN-END:variables
}
